#!/bin/bash

git clone https://github.com/monsterbunx/workflow-comfy.git temp
mv temp/{.,}* .
rm -r temp

docker compose -f comfy.yml up -d
echo "WORKFLOW DE COMFY INICIADO, SALIR CON CTRL P + Q"
docker attach comfy
